### ISSUE TITLE
用这种方式创建的房间 算活跃度么

### ISSUE THREAD

**Issue by nankedou** [sndmndss/dota2lobbycreater#1]
用这种方式创建的房间 算活跃度么

**Comment by sndmndss** [comment]
Yes, but it will be destroyed after 20 seconds, you can delete 21 line to avoid it. Now we are working on another rep, you can check it here: https://github.com/xaniyaa/d2bot

**Comment by nankedou** [comment]
有联系方式么 我正在做这方面的功能，我创建了房间 却无法计算活跃人数

**Comment by sndmndss** [comment]
You can write me on telegram: https://t.me/sndmndss
